language: python
python:
  - "3.6.5"

cache: pip3

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - coverage run -m unittest
  - coverage report
  - coverage
  - coveralls

#after_success:
  #- coveralls

  