language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls


# command to run tests
script:
  - py.test --cov
  - coverage report



after_success:
  - coveralls

  